# Generated by Django 5.2.6 on 2025-09-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_checkout_paid_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
