# Generated by Django 5.2.6 on 2025-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_order_price_remove_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
