# Generated by Django 5.2.6 on 2025-10-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_track_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
