# Generated by Django 5.2.6 on 2025-10-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_track_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='payment',
        ),
    ]
