# Generated by Django 5.2.6 on 2025-10-05 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_track_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='checkout',
        ),
    ]
